- name: install epel-release
  yum: 
    name: epel-release
    state: present

- name: install Remi 
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm

- name: copy remi-php72.repo
  copy:
    src: ../files/remi-php72.repo
    dest: /etc/yum.repos.d

- name: install php
  yum: name={{ item }} state=installed
  with_items:
    - php
    - php-devel
    - php-mbstring
    - php-mcrypt
    - php-pdo
    - php-mysqlnd
    - php-xml
    - php-pecl-mongodb
    - php-cli
    - php-pear
    - php-pecl-zip
    - php-gd



# - name: create php symbolic link
#   file:
#     src: "/bin/php72"
#     dest: "/bin/php"
#     state: link
  